22 parkplatzdetails editieren
TeamC2-Softwareprojekt/ParkBlazer pull request #53
Opened 2024-06-26 13:30 UTC by HauerichT

Ist inkl. 23-parkplätze-löschen

2024-06-27 15:30 UTC, Minerder requested changes
Sieht schonmal gut aus, aber ich habe ein paar Verbesserungen gefunden.

Mir ist aufgefallen, dass jeder User jeden Parkplatz editieren kann, indem man die URL ändert. Ist das gewollt?

Bei den `userParkingspots` kann man im `localStorage` seinen Namen manuell ändern und dann die Parkplätze von anderen Usern sehen. Das sollte nicht so sein.

Beim Ändern von Parkplätzen fehlen noch ein paar Sachen. Ich würde den Typ, den Preis pro Stunde und Start und End Datum noch ändern wollen.

2024-06-27 15:30 UTC, Minerder commented on ParkBlazerApp/src/pages/ParkingspotEdit.tsx
> +                setError("Parkplatz nicht gefunden.");
Error sollten auf Englisch sein

2024-07-01 13:56 UTC, HauerichT commented on ParkBlazerApp/src/pages/UserParkingspots.tsx
> +    const [loading, setLoading] = useState<boolean>(true);
Ich verstehe nicht genau was du meinst. Ich habe versucht es zu ersetzen, aber dann wird nicht mehr angezeigt, dass das Laden noch läuft.

2024-07-01 17:28 UTC, Minerder commented on ParkBlazerApp/src/pages/UserParkingspots.tsx
> +    const [loading, setLoading] = useState<boolean>(true);
So könnte man das Implementiern
```suggestion
    {!parkingSpots && !error ? (
      <IonCard>
          <IonCardContent>
            <IonText className="no-parkingspots-text" color="medium">Laden...</IonText>
            <IonSpinner name="crescent" />
          </IonCardContent>
      </IonCard>)
      : ...
```

2024-07-02 18:44 UTC, Minerder approved these changes

2024-07-03 13:39 UTC, merged